### ISSUE TITLE
logos should include a textual representation below each of them for those of us who do not recognize every logo

### ISSUE THREAD

**Issue by windbender** [erangeles/techstack#3]

**Comment by erangeles** [comment]
@windbender currently if you hover over the images you get a tooltip text of the name, but will add support for text below the logos.

**Comment by erangeles** [comment]
<img width="1306" alt="Screen Shot 2021-01-06 at 1 03 36 PM" src="https://user-images.githubusercontent.com/13124163/103809760-993c3480-501f-11eb-82f2-449cae4a136b.png">

@PulkitBanta FYI here is the change made for this ^
